### ISSUE TITLE
Termina el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-mirenguerra#1]
Buen trabajo @mirenguerra !

He estado mirando tu rama 'repeatExercise', algunas pistas mejorar lo que tienes avanzado en ella:

- [x] Mueve tus componentes a la carpeta 'components' y dales nombres más semánticos, por ejemplo 'MyComponent' podría llamarse 'App'.
- [x] Solo los archivos que contengan componentes deben nombrarse con la primera en mayúscula y camelCase. Un ejemplo es PokemonArray.js, vamos a cambiarle el nombre y a ponerlo en una carpeta que se llame data, utils... o algo por el estilo. Cada mochuelo a su olivo!
- [x] Como las props aun no están tan fresquitas como deberian, te propongo que el archivo con el array de pokemons lo importes en index.js, y lo vayas pasando por props hasta PokemonList que es dónde lo utilizas. Así practicamos más esta parte.
- [x] Como PokemonList pinta un listado de pokemons, un UL y sus LIS no vendrían mal
- [x] Elimina el código comentado
- [ ] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [ ] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Si tienes cualquier duda, avisa!

Al turrón

**Comment by mirenguerra** [comment]
Hola @nasivuela 

He seguido todos tus consejos y he mejorado mi ejercicio, pero he sido incapaz de publicar en GitHub Pages, aunque he seguido los pasos que tenemos en la documentación. Si pudieras darme alguna pista más sobre cómo hacerlo y decirme algo más sobre cómo seguir mejorando mi ejercicio sería genial. 

Gracias!!

**Comment by nasivuela** [comment]
@mirenguerra esto tiene muy buena pinta.

Para publicar en GP react, revisa tu package.json, la propiedad "homepage" tiene que estar a primer nivel.

Tambien hecho en falta un archivo de estilos por componente.

Cierro issue y te dejo recomendaciones para que sigas practicando:

- Añade una página de detalle por pokemkon.
- Añade una funcionalidad para seleccionar favoritos, siguendo estos pasos:
1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

![](https://media.giphy.com/media/B0FESgqrne9A4/giphy.gif)
